variables:
   WORKING_DIR: $CI_PROJECT_DIR/lxc
   ARTIFACTS_DIR: $CI_PROJECT_DIR/artifacts
   ARCH: amd64
   debci_quiet: 'false'

stages:
  - base
  - inherited

.build-base: &build-base
  stage: base
  image: registry.github.com/khulnasoft-lab/buildkit/ci-pipeline/autopkgtest
  before_script:
    # Remount /builds with the dev option if needed.
    # Since GitLab migrated to Google Container-Optimized OS & Docker 19.03.15
    # in August 2021, /builds is mounted with the option nodev, and it breaks
    # debootstrap. References:
    # * https://gitlab.com/kalilinux/build-scripts/kali-docker/-/issues/40
    # * https://gitlab.com/gitlab-com/gl-infra/production/-/issues/5184
    - |
        findmnt -no options -T . | grep -qw nodev && mount -vo remount,dev $(stat -c %m .) || true
    # Setup mount points, apparently required if host uses cgroups v1.
    # Dropped upstream in 36952e6, as Salsa hosts use cgroups v2, I guess.
    - |
        mount -t tmpfs cgroup_root /sys/fs/cgroup
        mkdir /sys/fs/cgroup/cpuset
        mkdir /sys/fs/cgroup/devices
        mount -t cgroup cpuset -o cpuset /sys/fs/cgroup/cpuset/
        mount -t cgroup devices -o devices /sys/fs/cgroup/devices
  script:
    # eatmydata can't be preloaded due to apparmor, remove it to avoid error messages
    - test -e /usr/bin/eatmydata && apt-get remove -y eatmydata
    - export
    # In case there is an underlying network already with the same network address, e.g. a runner
    # running on top of a libvirtd VM, we need to look for another network
    - |
        UNDERLYING_NET=0
        for n in $(seq 122 129); do
          bash -c "echo >/dev/tcp/192.168.${n}.1/53" \
            || { UNDERLYING_NET=${n} ; break; }
        done
        if [ "$UNDERLYING_NET" -eq 0 ]; then
          echo "unable to find an unused network" >&2
          exit 1
        fi
    - |
        cat >/etc/lxc/default.conf <<EOT
        lxc.net.0.type = veth
        lxc.net.0.link = lxcbr0
        lxc.net.0.flags = up
        lxc.net.0.hwaddr = 00:16:3e:xx:xx:xx
        lxc.apparmor.profile = unconfined
        EOT
    - |
        cat >/etc/default/lxc-net <<EOT
        USE_LXC_BRIDGE="true"
        EOT
    - |
        cat >/etc/lxc/lxc.conf <<EOT
        lxc.lxcpath=${WORKING_DIR}
        EOT
    - /etc/init.d/lxc-net restart || true
    - /etc/init.d/lxc start
    - /etc/init.d/lxc restart
    - /etc/init.d/libvirtd start

    - test "$UNDERLYING_NET" -ne "122" && echo "The default libvirtd network seems to be unavailble and will be be replaced by 192.168.${UNDERLYING_NET}.0/24"
    - |
        if [ "$UNDERLYING_NET" -ne 122 ] ; then
          virsh net-destroy default || true
          virsh net-dumpxml default > /tmp/default.xml
          sed -i -e "s/='192\.168\.122\.\([0-9]\+\)'/='192.168.${UNDERLYING_NET}.\1'/g" /tmp/default.xml
          virsh net-undefine default
          virsh net-define /tmp/default.xml
        fi

    - virsh net-start default
    - |
        if [ ! -e /usr/share/debci/bin/debci-generate-apt-sources ]; then
            for p in $(find ${CI_PROJECT_DIR}/patches -name \*.patch | sort); do
                patch -p1 -d /usr/share/debci <$p;
            done
        fi
    # Use http-staging.kali.org
    - debci setup --suite ${CI_JOB_NAME%%_*} --mirror http://http-staging.kali.org/kali/

  after_script:
    - mkdir -p ${ARTIFACTS_DIR}
    - tar -cf ${ARTIFACTS_DIR}/lxc-${ARCH}.tar --exclude /dev -C ${WORKING_DIR} .
    - md5sum ${ARTIFACTS_DIR}/lxc-${ARCH}.tar > ${ARTIFACTS_DIR}/lxc-${ARCH}.tar.md5

  artifacts:
    paths:
    - ${ARTIFACTS_DIR}
  retry:
    max: 1
    when:
      - script_failure

.build-inherited: &build-inherited
  stage: inherited
  image: debian
  # dependencies:
  #   - '<base-suite>'
  script:
    - mkdir -p "${WORKING_DIR}"
    - tar -C "${WORKING_DIR}" -xf "${ARTIFACTS_DIR}/lxc-${ARCH}.tar"
    - BASENAME=$(ls -1 "${WORKING_DIR}" | sed -e 's/^autopkgtest-//' -e "s/-${ARCH}"'$'"//")
    - mv "${WORKING_DIR}"/autopkgtest-${BASENAME}-${ARCH} "${WORKING_DIR}/autopkgtest-${CI_JOB_NAME%%_*}-${ARCH}"
    - echo "deb http://http-staging.kali.org/kali ${CI_JOB_NAME%%_*} main contrib non-free non-free-firmware" > "${WORKING_DIR}/autopkgtest-${CI_JOB_NAME%%_*}-${ARCH}/rootfs/etc/apt/sources.list.d/sci.list"
    - sed -i "s/${BASENAME}/${CI_JOB_NAME%%_*}/g" "${WORKING_DIR}/autopkgtest-${CI_JOB_NAME%%_*}-${ARCH}/config"
    - tar -cf "${ARTIFACTS_DIR}/lxc-${ARCH}.tar" --exclude /dev -C "${WORKING_DIR}" .
    - md5sum ${ARTIFACTS_DIR}/lxc-${ARCH}.tar > ${ARTIFACTS_DIR}/lxc-${ARCH}.tar.md5
  artifacts:
    paths:
    - ${ARTIFACTS_DIR}

kali-dev:
  extends: .build-base

kali-experimental:
  extends: .build-inherited
  dependencies:
    - kali-dev

kali-rolling:
  extends: .build-base
